/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AssetsBulkUpdateAcrRequestInnerAssetInner : Each object can contain a single instance of the properties described below. You can combine multiple instances of this object, each containing a different single property.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetsBulkUpdateAcrRequestInnerAssetInner {
    /// The UUID for a specific asset. Use this value as the unique key for the asset.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Fully-qualified domain names (FQDNs) associated with the asset or assets.
    #[serde(rename = "fqdn", skip_serializing_if = "Option::is_none")]
    pub fqdn: Option<Vec<String>>,
    /// MAC addresses associated with the asset or assets.
    #[serde(rename = "mac_address", skip_serializing_if = "Option::is_none")]
    pub mac_address: Option<Vec<String>>,
    /// The NetBIOS name for the asset.
    #[serde(rename = "netbios_name", skip_serializing_if = "Option::is_none")]
    pub netbios_name: Option<String>,
    /// IPv4 addresses associated with the asset or assets.
    #[serde(rename = "ipv4", skip_serializing_if = "Option::is_none")]
    pub ipv4: Option<Vec<String>>,
}

impl AssetsBulkUpdateAcrRequestInnerAssetInner {
    /// Each object can contain a single instance of the properties described below. You can combine multiple instances of this object, each containing a different single property.
    pub fn new() -> AssetsBulkUpdateAcrRequestInnerAssetInner {
        AssetsBulkUpdateAcrRequestInnerAssetInner {
            id: None,
            fqdn: None,
            mac_address: None,
            netbios_name: None,
            ipv4: None,
        }
    }
}


