/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetTagsInner {
    /// The tag category.
    #[serde(rename = "key")]
    pub key: String,
    /// The tag value.
    #[serde(rename = "value")]
    pub value: Vec<String>,
}

impl AssetTagsInner {
    pub fn new(key: String, value: Vec<String>) -> AssetTagsInner {
        AssetTagsInner {
            key,
            value,
        }
    }
}


