/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AssetsBulkDeleteRequestQueryAndInner : The query for selecting the assets to delete. Includes an asset attribute, an operator, and a value. To get the list of supported filters, use the [GET /filters/workbenches/assets](ref:io-filters-assets-list) endpoint.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetsBulkDeleteRequestQueryAndInner {
    /// The name of the asset attribute to match. Asset attributes can include tags, for example, `tag.city`.
    #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
    pub field: Option<String>,
    /// The operator to apply to the matched value, for example, `eq` (equals), `neq` (does not equal), or `match` (contains).
    #[serde(rename = "operator", skip_serializing_if = "Option::is_none")]
    pub operator: Option<String>,
    /// The asset attribute value to match.   **Note:** The value is case sensitive when used with the `match` (contains) or `nmatch` (does not contain) operators.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl AssetsBulkDeleteRequestQueryAndInner {
    /// The query for selecting the assets to delete. Includes an asset attribute, an operator, and a value. To get the list of supported filters, use the [GET /filters/workbenches/assets](ref:io-filters-assets-list) endpoint.
    pub fn new() -> AssetsBulkDeleteRequestQueryAndInner {
        AssetsBulkDeleteRequestQueryAndInner {
            field: None,
            operator: None,
            value: None,
        }
    }
}


