/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AssetsBulkMove202Response : Bulk operations results. Contains the number of assets affected by the operation (moved or deleted).



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetsBulkMove202Response {
    /// The number of assets affected by the operation.
    #[serde(rename = "asset_count", skip_serializing_if = "Option::is_none")]
    pub asset_count: Option<i32>,
}

impl AssetsBulkMove202Response {
    /// Bulk operations results. Contains the number of assets affected by the operation (moved or deleted).
    pub fn new() -> AssetsBulkMove202Response {
        AssetsBulkMove202Response {
            asset_count: None,
        }
    }
}


