/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AssetsListAssets200ResponseAssetsInnerAcrDriversInner : Information about an asset characteristic that factored into the ACR score calculation.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetsListAssets200ResponseAssetsInnerAcrDriversInner {
    /// The type of characteristic.
    #[serde(rename = "driver_name", skip_serializing_if = "Option::is_none")]
    pub driver_name: Option<String>,
    /// The characteristic value.
    #[serde(rename = "driver_value", skip_serializing_if = "Option::is_none")]
    pub driver_value: Option<Vec<String>>,
}

impl AssetsListAssets200ResponseAssetsInnerAcrDriversInner {
    /// Information about an asset characteristic that factored into the ACR score calculation.
    pub fn new() -> AssetsListAssets200ResponseAssetsInnerAcrDriversInner {
        AssetsListAssets200ResponseAssetsInnerAcrDriversInner {
            driver_name: None,
            driver_value: None,
        }
    }
}


