/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetsListAssets200ResponseAssetsInnerSourcesInnerInner {
    /// The name of the entity that reported the asset details. Sources can include sensors, connectors, and API imports. Source names can be customized by your organization (for example, you specify a name when you import asset records). If your organization does not customize source names, system-generated names include:  - AWS—You obtained the asset data from an Amazon Web Services connector.  - NESSUS_AGENT—You obtained the asset data obtained from a Nessus agent scan.  - PVS—You obtained the asset data from a Nessus Network Monitor (NNM) scan.  - NESSUS_SCAN—You obtained the asset data from a Nessus scan.  - WAS—You obtained the asset data from a  Web Application Scanning scan.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The ISO timestamp when the source first reported the asset.
    #[serde(rename = "first_seen", skip_serializing_if = "Option::is_none")]
    pub first_seen: Option<String>,
    /// The ISO timestamp when the source last reported the asset.
    #[serde(rename = "last_seen", skip_serializing_if = "Option::is_none")]
    pub last_seen: Option<String>,
}

impl AssetsListAssets200ResponseAssetsInnerSourcesInnerInner {
    pub fn new() -> AssetsListAssets200ResponseAssetsInnerSourcesInnerInner {
        AssetsListAssets200ResponseAssetsInnerSourcesInnerInner {
            name: None,
            first_seen: None,
            last_seen: None,
        }
    }
}


