/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetsImport200Response {
    /// The asset import job UUID.
    #[serde(rename = "asset_import_job_uuid", skip_serializing_if = "Option::is_none")]
    pub asset_import_job_uuid: Option<String>,
}

impl AssetsImport200Response {
    pub fn new() -> AssetsImport200Response {
        AssetsImport200Response {
            asset_import_job_uuid: None,
        }
    }
}


