/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetsImportRequest {
    /// An array of asset objects to import. Each asset object requires a value for at least one of the following properties: fqdn, ipv4, netbios\\_name, mac\\_address.  For an example of this request body, see [Add Asset Data to Tenable.io](doc:add-asset-data-to-tenableio). For the complete list of importable asset attributes, see [Common Asset Attributes](doc:common-asset-attributes#section-asset-attribute-definitions).  **Caution:** AWS, Azure, and GCP asset data must be imported separately even if the data is associated with the same asset. For example, Azure imports should only contain Azure data in the payload. The import fails if AWS data is included with the Azure data in the payload.
    #[serde(rename = "assets")]
    pub assets: Vec<crate::models::AssetsImportRequestAssetsInner>,
    /// A user-defined name for the source of the import containing the asset records. You can specify only one source for each import.
    #[serde(rename = "source")]
    pub source: String,
}

impl AssetsImportRequest {
    pub fn new(assets: Vec<crate::models::AssetsImportRequestAssetsInner>, source: String) -> AssetsImportRequest {
        AssetsImportRequest {
            assets,
            source,
        }
    }
}


