/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetsAssetInfo200ResponseTagsInner {
    /// The UUID of the tag.
    #[serde(rename = "tag_uuid", skip_serializing_if = "Option::is_none")]
    pub tag_uuid: Option<String>,
    /// The tag category (the first half of the category:value pair).
    #[serde(rename = "tag_key", skip_serializing_if = "Option::is_none")]
    pub tag_key: Option<String>,
    /// The tag value (the second half of the category:value pair).
    #[serde(rename = "tag_value", skip_serializing_if = "Option::is_none")]
    pub tag_value: Option<String>,
    /// The UUID of the user who assigned the tag to the asset.
    #[serde(rename = "added_by", skip_serializing_if = "Option::is_none")]
    pub added_by: Option<String>,
    /// The ISO timestamp when the tag was assigned to the asset.
    #[serde(rename = "added_at", skip_serializing_if = "Option::is_none")]
    pub added_at: Option<String>,
}

impl AssetsAssetInfo200ResponseTagsInner {
    pub fn new() -> AssetsAssetInfo200ResponseTagsInner {
        AssetsAssetInfo200ResponseTagsInner {
            tag_uuid: None,
            tag_key: None,
            tag_value: None,
            added_by: None,
            added_at: None,
        }
    }
}


