/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AssetsBulkUpdateAcrRequestInner : Parameters to update the ACR for an asset. For a request body example, see \"Update ACR for assets\" in [Bulk Asset Operations](doc:bulk-asset-operations).



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetsBulkUpdateAcrRequestInner {
    /// The ACR score you want to assign to the asset. The ACR must be an integer from 1 to 10.
    #[serde(rename = "acr_score")]
    pub acr_score: i32,
    /// The reasons you are updating the ACR for the assets. Supported values include:   - Business Critical  - In Scope For Compliance  - Existing Mitigation Control  - Dev only   - Key drivers does not match   - Other  This parameter corresponds to the **Overwrite Reasoning** parameter when editing an ACR in the Tenable.io Lumin user interface. For more information, see [Edit an ACR](https://docs.tenable.com/vulnerability-management/Content/Lumin/LuminEditACR.htm).
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<Vec<Reason>>,
    /// Any notes you want to add to clarify the circumstances behind the update. This parameter corresponds to the **Note** parameter when editing an ACR in the Tenable.io Lumin user interface. For more information, see [Edit an ACR](https://docs.tenable.com/vulnerability-management/Content/Lumin/LuminEditACR.htm).  
    #[serde(rename = "note", skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    /// The identifiers of the assets to update to the specified ACR. At least one asset object is required in this array.
    #[serde(rename = "asset")]
    pub asset: Vec<crate::models::AssetsBulkUpdateAcrRequestInnerAssetInner>,
}

impl AssetsBulkUpdateAcrRequestInner {
    /// Parameters to update the ACR for an asset. For a request body example, see \"Update ACR for assets\" in [Bulk Asset Operations](doc:bulk-asset-operations).
    pub fn new(acr_score: i32, asset: Vec<crate::models::AssetsBulkUpdateAcrRequestInnerAssetInner>) -> AssetsBulkUpdateAcrRequestInner {
        AssetsBulkUpdateAcrRequestInner {
            acr_score,
            reason: None,
            note: None,
            asset,
        }
    }
}

/// The reasons you are updating the ACR for the assets. Supported values include:   - Business Critical  - In Scope For Compliance  - Existing Mitigation Control  - Dev only   - Key drivers does not match   - Other  This parameter corresponds to the **Overwrite Reasoning** parameter when editing an ACR in the Tenable.io Lumin user interface. For more information, see [Edit an ACR](https://docs.tenable.com/vulnerability-management/Content/Lumin/LuminEditACR.htm).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Reason {
    #[serde(rename = "Business Critical")]
    BusinessCritical,
    #[serde(rename = "In Scope For Compliance")]
    InScopeForCompliance,
    #[serde(rename = "Existing Mitigation Control")]
    ExistingMitigationControl,
    #[serde(rename = "Dev only")]
    DevOnly,
    #[serde(rename = "Key drivers does not match")]
    KeyDriversDoesNotMatch,
    #[serde(rename = "Other")]
    Other,
}

impl Default for Reason {
    fn default() -> Reason {
        Self::BusinessCritical
    }
}

