/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AssetsBulkMoveRequest : The parameters for moving assets from one network to another.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetsBulkMoveRequest {
    /// The UUID of the network currently associated with the assets. Use the [GET /networks](ref:networks-list) endpoint with the name attribute as filter to find the UUID of the network.
    #[serde(rename = "source")]
    pub source: String,
    /// The UUID of the network to associate with the specified assets. Use the [GET /networks](ref:networks-list) endpoint with the name filter to find the UUID of the network.
    #[serde(rename = "destination")]
    pub destination: String,
    /// The IPv4 addresses of the assets to move. The addresses can be represented as a comma-separated list, a range, or CIDR, for example `1.1.1.1, 2.2.2.2-2.2.2.200, 3.3.3.0/24`.
    #[serde(rename = "targets")]
    pub targets: String,
}

impl AssetsBulkMoveRequest {
    /// The parameters for moving assets from one network to another.
    pub fn new(source: String, destination: String, targets: String) -> AssetsBulkMoveRequest {
        AssetsBulkMoveRequest {
            source,
            destination,
            targets,
        }
    }
}


