/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetsBulkDeleteRequest {
    /// Indicates whether or not to completely remove the asset from your licensed asset count along with all related data. If this parameter is omitted, Tenable.io uses the default value of `false`.
    #[serde(rename = "hard_delete", skip_serializing_if = "Option::is_none")]
    pub hard_delete: Option<bool>,
    #[serde(rename = "query")]
    pub query: Box<crate::models::AssetsBulkDeleteRequestQuery>,
}

impl AssetsBulkDeleteRequest {
    pub fn new(query: crate::models::AssetsBulkDeleteRequestQuery) -> AssetsBulkDeleteRequest {
        AssetsBulkDeleteRequest {
            hard_delete: None,
            query: Box::new(query),
        }
    }
}


