/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditorPluginDescription200Response {
    #[serde(rename = "plugindescription", skip_serializing_if = "Option::is_none")]
    pub plugindescription: Option<Box<crate::models::EditorPluginDescription200ResponsePlugindescription>>,
}

impl EditorPluginDescription200Response {
    pub fn new() -> EditorPluginDescription200Response {
        EditorPluginDescription200Response {
            plugindescription: None,
        }
    }
}


