/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EditorListTemplates200ResponseInner : Templates are used to create scans or policies with predefined parameters.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditorListTemplates200ResponseInner {
    /// If `true`, the template is not supported.
    #[serde(rename = "unsupported", skip_serializing_if = "Option::is_none")]
    pub unsupported: Option<bool>,
    /// If `true`, the template is only available on the cloud.
    #[serde(rename = "cloud_only", skip_serializing_if = "Option::is_none")]
    pub cloud_only: Option<bool>,
    /// The description of the template.
    #[serde(rename = "desc", skip_serializing_if = "Option::is_none")]
    pub desc: Option<String>,
    /// If `true`, the template is only available for subscribers.
    #[serde(rename = "subscription_only", skip_serializing_if = "Option::is_none")]
    pub subscription_only: Option<bool>,
    /// If `true`, the template can be used for Web Application Scanning only.
    #[serde(rename = "is_was", skip_serializing_if = "Option::is_none")]
    pub is_was: Option<bool>,
    /// The long name of the template.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// If `true`, the template can only be used for agent scans.
    #[serde(rename = "is_agent", skip_serializing_if = "Option::is_none")]
    pub is_agent: Option<bool>,
    /// The UUID for the template. Use this value to specify the template when creating scans and policies.
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    /// If `true`, can only be used by manager.
    #[serde(rename = "manager_only", skip_serializing_if = "Option::is_none")]
    pub manager_only: Option<bool>,
    /// The short name of the template.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl EditorListTemplates200ResponseInner {
    /// Templates are used to create scans or policies with predefined parameters.
    pub fn new() -> EditorListTemplates200ResponseInner {
        EditorListTemplates200ResponseInner {
            unsupported: None,
            cloud_only: None,
            desc: None,
            subscription_only: None,
            is_was: None,
            title: None,
            is_agent: None,
            uuid: None,
            manager_only: None,
            name: None,
        }
    }
}


