/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportsVulnsDownloadChunk200ResponsePluginInnerCvss3VectorInner {
    /// The CVSSv2 Attack Vector (AV) metric for the vulnerability the plugin covers. Possible values include:  - Network—Corresponds to the Network (N) value for the AV metric.   - Adjacent Network—Corresponds to the Adjacent Network (A) value for the AV metric.   - Local—Corresponds to the Local (L) value for the AV metric
    #[serde(rename = "access_vector", skip_serializing_if = "Option::is_none")]
    pub access_vector: Option<String>,
    /// The CVSSv3 Access Complexity (AC) metric for the vulnerability the plugin covers. Possible values include:   - H—High  - M—Medium  - L—Low
    #[serde(rename = "access_complexity", skip_serializing_if = "Option::is_none")]
    pub access_complexity: Option<String>,
    /// The CVSSv2 Authentication (Au) metric for the vulnerability the plugin covers. Possible values include:  - None required—Corresponds to the None (N) value for the Au metric.   - Requires-single-instance—Corresponds to the Single (S) value for the Au metric.   - Requires-multiple-instances—Corresponds to the Multiple (M) value for the Au metric
    #[serde(rename = "authentication", skip_serializing_if = "Option::is_none")]
    pub authentication: Option<String>,
    /// The CVSSv3 confidentiality impact metric of the vulnerability the plugin covers to the vulnerable component. Possible values include:   - H—High  - L—Low  - N—None
    #[serde(rename = "confidentiality_impact", skip_serializing_if = "Option::is_none")]
    pub confidentiality_impact: Option<String>,
    /// The CVSSv3 integrity impact metric for the vulnerability the plugin covers. Possible values include:  - H—High  - L—Low  - N—None
    #[serde(rename = "integrity_impact", skip_serializing_if = "Option::is_none")]
    pub integrity_impact: Option<String>,
    /// The CVSSv2 availability impact metric for the vulnerability the plugin covers. Possible values include:   - H—High  - L—Low  - N—None
    #[serde(rename = "availability_impact", skip_serializing_if = "Option::is_none")]
    pub availability_impact: Option<String>,
    /// The complete `cvss3_vector` metrics and result values for the vulnerability the plugin covers in a condensed and coded format. For example, `AV:N/AC:M/Au:N/C:C/I:C/A:C`.
    #[serde(rename = "raw", skip_serializing_if = "Option::is_none")]
    pub raw: Option<String>,
}

impl ExportsVulnsDownloadChunk200ResponsePluginInnerCvss3VectorInner {
    pub fn new() -> ExportsVulnsDownloadChunk200ResponsePluginInnerCvss3VectorInner {
        ExportsVulnsDownloadChunk200ResponsePluginInnerCvss3VectorInner {
            access_vector: None,
            access_complexity: None,
            authentication: None,
            confidentiality_impact: None,
            integrity_impact: None,
            availability_impact: None,
            raw: None,
        }
    }
}


