/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ExportsVulnsDownloadChunk200ResponsePluginInnerVpr : Information about the Vulnerability Priority Rating (VPR) for the vulnerability.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportsVulnsDownloadChunk200ResponsePluginInnerVpr {
    /// The Vulnerability Priority Rating (VPR) for the vulnerability. If a plugin is designed to detect multiple vulnerabilities, the VPR represents the highest value calculated for a vulnerability associated with the plugin. For more information, see <a href=\"https://docs.tenable.com/vulnerability-management/Content/Analysis/RiskMetrics.htm\" target=\"_blank\">Severity vs. VPR</a> in the <i>Tenable Vulnerability Management User Guide</i>.
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<i32>,
    /// The key drivers Tenable uses to calculate a vulnerability's VPR. For more information, see [Vulnerability Priority Rating Drivers](doc:vpr-drivers-tio).
    #[serde(rename = "drivers", skip_serializing_if = "Option::is_none")]
    pub drivers: Option<serde_json::Value>,
    /// The ISO timestamp when Tenable Vulnerability Management last imported the VPR for this vulnerability. Tenable Vulnerability Management imports a VPR value the first time you scan a vulnerability on your network. Then, Tenable Vulnerability Management automatically re-imports new and updated VPR values daily.
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
}

impl ExportsVulnsDownloadChunk200ResponsePluginInnerVpr {
    /// Information about the Vulnerability Priority Rating (VPR) for the vulnerability.
    pub fn new() -> ExportsVulnsDownloadChunk200ResponsePluginInnerVpr {
        ExportsVulnsDownloadChunk200ResponsePluginInnerVpr {
            score: None,
            drivers: None,
            updated: None,
        }
    }
}


