/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportsAssetsRequestExportRequest {
    /// Specifies the number of assets per exported chunk. The range is 100-10000. If you specify a value outside of that range, Tenable Vulnerability Management returns a 400 error.   **Note:** Using smaller chunks size can improve performance. Tenable does not recommend using a chunk size larger than 5000 as the potential for an error increases above this amount.
    #[serde(rename = "chunk_size")]
    pub chunk_size: i32,
    /// Specifies whether or not to include open port findings from info-level plugins. If this parameter is omitted, Tenable Vulnerability Management uses a default value of `false`.  **Caution:** Including open port findings can significantly increase the size of the API response and exports take longer to complete.
    #[serde(rename = "include_open_ports", skip_serializing_if = "Option::is_none")]
    pub include_open_ports: Option<bool>,
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<Box<crate::models::ExportsAssetsRequestExportRequestFilters>>,
}

impl ExportsAssetsRequestExportRequest {
    pub fn new(chunk_size: i32) -> ExportsAssetsRequestExportRequest {
        ExportsAssetsRequestExportRequest {
            chunk_size,
            include_open_ports: None,
            filters: None,
        }
    }
}


