/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ExportsVulnsRequestExportRequestFiltersVprScore : Returns vulnerabilities with the specified Vulnerability Priority Rating (VPR) score or scores. You can combine properties in this object to specify VPR ranges. For example, to export vulnerabilities greater than or equal to 9.0 but lesser than or equal to 9.9, the object would contain a `gte` property of 9.0 and an `lte` property of 9.9.   For more information about VPR, see <a href=\"https://docs.tenable.com/vulnerability-management/Content/Analysis/RiskMetrics.htm\" target=\"_blank\">Severity vs. VPR</a> in the <i>Tenable Vulnerability Management User Guide</i>.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportsVulnsRequestExportRequestFiltersVprScore {
    /// Returns vulnerabilities with a VPR equal to the specified score or scores. This property cannot be combined with the following range operators: `lt`, `gt`, `lte`, or `gte`.
    #[serde(rename = "eq", skip_serializing_if = "Option::is_none")]
    pub eq: Option<Vec<f32>>,
    /// Returns vulnerabilities with a VPR not equal to the specified score or scores. This property can be combined with the `eq` property.
    #[serde(rename = "neq", skip_serializing_if = "Option::is_none")]
    pub neq: Option<Vec<f32>>,
    /// Returns vulnerabilities with a VPR greater than the specified score. This property cannot be combined with the `eq` property.
    #[serde(rename = "gt", skip_serializing_if = "Option::is_none")]
    pub gt: Option<f32>,
    /// Returns vulnerabilities with a VPR greater than or equal to the specified score. This property cannot be combined with the `eq` property.
    #[serde(rename = "gte", skip_serializing_if = "Option::is_none")]
    pub gte: Option<f32>,
    /// Returns vulnerabilities with a VPR lesser than the specified score. This property cannot be combined with the `eq` property.
    #[serde(rename = "lt", skip_serializing_if = "Option::is_none")]
    pub lt: Option<f32>,
    /// Returns vulnerabilities with a VPR lesser than or equal to the specified score. This property cannot be combined with the `eq` property.
    #[serde(rename = "lte", skip_serializing_if = "Option::is_none")]
    pub lte: Option<f32>,
}

impl ExportsVulnsRequestExportRequestFiltersVprScore {
    /// Returns vulnerabilities with the specified Vulnerability Priority Rating (VPR) score or scores. You can combine properties in this object to specify VPR ranges. For example, to export vulnerabilities greater than or equal to 9.0 but lesser than or equal to 9.9, the object would contain a `gte` property of 9.0 and an `lte` property of 9.9.   For more information about VPR, see <a href=\"https://docs.tenable.com/vulnerability-management/Content/Analysis/RiskMetrics.htm\" target=\"_blank\">Severity vs. VPR</a> in the <i>Tenable Vulnerability Management User Guide</i>.
    pub fn new() -> ExportsVulnsRequestExportRequestFiltersVprScore {
        ExportsVulnsRequestExportRequestFiltersVprScore {
            eq: None,
            neq: None,
            gt: None,
            gte: None,
            lt: None,
            lte: None,
        }
    }
}


