/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportsVulnsDownloadChunk200ResponsePluginInnerCvssVectorInner {
    /// The CVSSv2 Access Vector (AV) metric for the vulnerability the plugin covers. Possible values include:   - L—Local  - A—Adjacent Network  - N—Network
    #[serde(rename = "access_vector", skip_serializing_if = "Option::is_none")]
    pub access_vector: Option<String>,
    /// The CVSSv2 Access Complexity (AC) metric for the vulnerability the plugin covers. Possible values include:  - H—High  - M—Medium  - L—Low
    #[serde(rename = "access_complexity", skip_serializing_if = "Option::is_none")]
    pub access_complexity: Option<String>,
    /// The CVSSv2 Authentication (Au) metric for the vulnerability the plugin covers. Possible values include:   - N—None  - S—Single  - M—Multiple
    #[serde(rename = "authentication", skip_serializing_if = "Option::is_none")]
    pub authentication: Option<String>,
    /// The CVSSv2 confidentiality impact metric for the vulnerability the plugin covers. Possible values include:   - N—None  - P—Partial  - C—Complete
    #[serde(rename = "confidentiality_impact", skip_serializing_if = "Option::is_none")]
    pub confidentiality_impact: Option<String>,
    /// The CVSSv2 integrity impact metric for the vulnerability the plugin covers. Possible values include:   - N—None  - P—Partial  - C—Complete
    #[serde(rename = "integrity_impact", skip_serializing_if = "Option::is_none")]
    pub integrity_impact: Option<String>,
    /// The CVSSv2 availability impact metric for the vulnerability the plugin covers. Possible values include:   - N—None  - P—Partial  - C—Complete
    #[serde(rename = "availability_impact", skip_serializing_if = "Option::is_none")]
    pub availability_impact: Option<String>,
    /// The complete `cvss_vector` metrics and result values for the vulnerability the plugin covers in a condensed and coded format. For example, `AV:N/AC:M/Au:N/C:C/I:C/A:C`.
    #[serde(rename = "raw", skip_serializing_if = "Option::is_none")]
    pub raw: Option<String>,
}

impl ExportsVulnsDownloadChunk200ResponsePluginInnerCvssVectorInner {
    pub fn new() -> ExportsVulnsDownloadChunk200ResponsePluginInnerCvssVectorInner {
        ExportsVulnsDownloadChunk200ResponsePluginInnerCvssVectorInner {
            access_vector: None,
            access_complexity: None,
            authentication: None,
            confidentiality_impact: None,
            integrity_impact: None,
            availability_impact: None,
            raw: None,
        }
    }
}


