/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportsAssetsExportStatus200Response {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<crate::models::ExportsAssetsExportStatus200ResponseStatus>>,
    /// A comma-separated list of completed chunks available for download.
    #[serde(rename = "chunks_available", skip_serializing_if = "Option::is_none")]
    pub chunks_available: Option<Vec<i32>>,
}

impl ExportsAssetsExportStatus200Response {
    pub fn new() -> ExportsAssetsExportStatus200Response {
        ExportsAssetsExportStatus200Response {
            status: None,
            chunks_available: None,
        }
    }
}


