/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportsVulnsDownloadChunk200ResponseScanInner {
    /// The ISO timestamp when the scan completed.
    #[serde(rename = "completed_at", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<String>,
    /// The schedule UUID for the scan that found the vulnerability.
    #[serde(rename = "schedule_uuid", skip_serializing_if = "Option::is_none")]
    pub schedule_uuid: Option<String>,
    /// The ISO timestamp when the scan started.
    #[serde(rename = "started_at", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<String>,
    /// The UUID of the scan that found the vulnerability.
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
}

impl ExportsVulnsDownloadChunk200ResponseScanInner {
    pub fn new() -> ExportsVulnsDownloadChunk200ResponseScanInner {
        ExportsVulnsDownloadChunk200ResponseScanInner {
            completed_at: None,
            schedule_uuid: None,
            started_at: None,
            uuid: None,
        }
    }
}


