/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportsVulnsDownloadChunk200ResponsePortInner {
    /// The port the scanner used to communicate with the asset.
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<String>,
    /// The protocol the scanner used to communicate with the asset.
    #[serde(rename = "protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,
    /// The service the scanner used to communicate with the asset.
    #[serde(rename = "service", skip_serializing_if = "Option::is_none")]
    pub service: Option<String>,
}

impl ExportsVulnsDownloadChunk200ResponsePortInner {
    pub fn new() -> ExportsVulnsDownloadChunk200ResponsePortInner {
        ExportsVulnsDownloadChunk200ResponsePortInner {
            port: None,
            protocol: None,
            service: None,
        }
    }
}


