/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ExportsAssetsExportStatus200ResponseStatus : Information about the export job.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportsAssetsExportStatus200ResponseStatus {
    /// The status of the export request. Possible values include:  - QUEUED—Tenable Vulnerability Management has queued the export request until it completes other requests currently in process.  - PROCESSING—Tenable Vulnerability Management has started processing the export request.  - FINISHED—Tenable Vulnerability Management has completed processing the export request. The list of chunks is complete.  - CANCELLED—An administrator has cancelled the export request.  - ERROR—Tenable Vulnerability Management encountered an error while processing the export request. Tenable recommends that you retry the request. If the status persists on retry, contact Support.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// A list of completed chunks available for download.
    #[serde(rename = "chunks_available", skip_serializing_if = "Option::is_none")]
    pub chunks_available: Option<Vec<i32>>,
}

impl ExportsAssetsExportStatus200ResponseStatus {
    /// Information about the export job.
    pub fn new() -> ExportsAssetsExportStatus200ResponseStatus {
        ExportsAssetsExportStatus200ResponseStatus {
            status: None,
            chunks_available: None,
        }
    }
}


