/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportsAssetsDownloadChunk200ResponseOpenPortsInner {
    /// The open port number.
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
    /// The communication protocol corresponding to the open port.
    #[serde(rename = "protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,
    /// The names of the services associated with the open port.
    #[serde(rename = "service_names", skip_serializing_if = "Option::is_none")]
    pub service_names: Option<Vec<String>>,
    /// The ISO timestamp when the source first detected the open port on the asset.
    #[serde(rename = "first_seen", skip_serializing_if = "Option::is_none")]
    pub first_seen: Option<String>,
    /// The ISO timestamp when the source last detected the open port on the asset.
    #[serde(rename = "last_seen", skip_serializing_if = "Option::is_none")]
    pub last_seen: Option<String>,
}

impl ExportsAssetsDownloadChunk200ResponseOpenPortsInner {
    pub fn new() -> ExportsAssetsDownloadChunk200ResponseOpenPortsInner {
        ExportsAssetsDownloadChunk200ResponseOpenPortsInner {
            port: None,
            protocol: None,
            service_names: None,
            first_seen: None,
            last_seen: None,
        }
    }
}


