/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportsVulnsDownloadChunk200ResponseAssetInner {
    /// The UUID of the agent that performed the scan where the vulnerability was found.
    #[serde(rename = "agent_uuid", skip_serializing_if = "Option::is_none")]
    pub agent_uuid: Option<String>,
    /// The BIOS UUID of the asset where the vulnerability was found.
    #[serde(rename = "bios_uuid", skip_serializing_if = "Option::is_none")]
    pub bios_uuid: Option<String>,
    /// The type of asset where the vulnerability was found.
    #[serde(rename = "device_type", skip_serializing_if = "Option::is_none")]
    pub device_type: Option<String>,
    /// The fully-qualified domain name of the asset where a scan found the vulnerability.
    #[serde(rename = "fqdn", skip_serializing_if = "Option::is_none")]
    pub fqdn: Option<String>,
    /// The host name of the asset where a scan found the vulnerability.
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    /// The UUID of the asset where a scan found the vulnerability.
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    /// The IPv6 address of the asset where a scan found the vulnerability.
    #[serde(rename = "ipv6", skip_serializing_if = "Option::is_none")]
    pub ipv6: Option<String>,
    /// The last date credentials were used successfully to scan the asset.
    #[serde(rename = "last_authenticated_results", skip_serializing_if = "Option::is_none")]
    pub last_authenticated_results: Option<String>,
    /// The last date when the asset was scanned without using credentials
    #[serde(rename = "last_unauthenticated_results", skip_serializing_if = "Option::is_none")]
    pub last_unauthenticated_results: Option<String>,
    /// The MAC address of the asset where a scan found the vulnerability.
    #[serde(rename = "mac_address", skip_serializing_if = "Option::is_none")]
    pub mac_address: Option<String>,
    /// The NETBIOS name of the asset where a scan found the vulnerability.
    #[serde(rename = "netbios_name", skip_serializing_if = "Option::is_none")]
    pub netbios_name: Option<String>,
    /// The NETBIOS workgroup of the asset where a scan found the vulnerability.
    #[serde(rename = "netbios_workgroup", skip_serializing_if = "Option::is_none")]
    pub netbios_workgroup: Option<String>,
    /// The operating system of the asset where a scan found the vulnerability.
    #[serde(rename = "operating_system", skip_serializing_if = "Option::is_none")]
    pub operating_system: Option<String>,
    /// The ID of the network object associated with scanners that identified the asset. The default network ID is `00000000-0000-0000-0000-000000000000`. For more information about network objects, see [Manage Networks](doc:manage-networks-tio).
    #[serde(rename = "network_id", skip_serializing_if = "Option::is_none")]
    pub network_id: Option<String>,
    /// A value specifying whether Tenable Vulnerability Management tracks the asset in the asset management system. Tenable Vulnerability Management still assigns untracked assets identifiers in scan results, but these identifiers change with each new scan of the asset. This parameter is relevant to PCI-type scans and in certain cases where there is not enough information in a scan to identify the asset. Untracked assets appear in the scan history, but do not appear in workbenches or reports.
    #[serde(rename = "tracked", skip_serializing_if = "Option::is_none")]
    pub tracked: Option<bool>,
}

impl ExportsVulnsDownloadChunk200ResponseAssetInner {
    pub fn new() -> ExportsVulnsDownloadChunk200ResponseAssetInner {
        ExportsVulnsDownloadChunk200ResponseAssetInner {
            agent_uuid: None,
            bios_uuid: None,
            device_type: None,
            fqdn: None,
            hostname: None,
            uuid: None,
            ipv6: None,
            last_authenticated_results: None,
            last_unauthenticated_results: None,
            mac_address: None,
            netbios_name: None,
            netbios_workgroup: None,
            operating_system: None,
            network_id: None,
            tracked: None,
        }
    }
}


