/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileUpload200Response {
    /// The name of the uploaded file. If the file with the same name already exists, Tenable.io appends an underscore with a number. For example, `scan-targets_1.txt`. Use this attribute value when referencing the file for subsequent requests.
    #[serde(rename = "fileuploaded", skip_serializing_if = "Option::is_none")]
    pub fileuploaded: Option<String>,
}

impl FileUpload200Response {
    pub fn new() -> FileUpload200Response {
        FileUpload200Response {
            fileuploaded: None,
        }
    }
}


