/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FoldersCreateRequest {
    /// The name of the folder.  **Note:** Folder names must be unique. Folder names can include any UTF-8 characters.
    #[serde(rename = "name")]
    pub name: String,
}

impl FoldersCreateRequest {
    pub fn new(name: String) -> FoldersCreateRequest {
        FoldersCreateRequest {
            name,
        }
    }
}


