/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FoldersCreate200Response {
    /// The ID of the created folder.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
}

impl FoldersCreate200Response {
    pub fn new() -> FoldersCreate200Response {
        FoldersCreate200Response {
            id: None,
        }
    }
}


