/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoExportsComplianceDownload200ResponseInnerReferenceInner {
    /// The name of the compliance framework.
    #[serde(rename = "framework", skip_serializing_if = "Option::is_none")]
    pub framework: Option<String>,
    /// The specific control within the compliance framework.
    #[serde(rename = "control", skip_serializing_if = "Option::is_none")]
    pub control: Option<String>,
}

impl IoExportsComplianceDownload200ResponseInnerReferenceInner {
    pub fn new() -> IoExportsComplianceDownload200ResponseInnerReferenceInner {
        IoExportsComplianceDownload200ResponseInnerReferenceInner {
            framework: None,
            control: None,
        }
    }
}


