/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoExportsComplianceCreateRequest {
    /// Specifies the number of compliance findings per exported chunk. The range is 50-10000. If your request omits the `num_findings` body parameter, the value defaults to `5000`. If you specify a value outside of the supported range, Tenable Vulnerability Management uses the upper or lower-bound value.
    #[serde(rename = "num_findings")]
    pub num_findings: i32,
    /// A list of asset UUIDs for which you want to return compliance data. The list can contain a maximum of 200 asset UUIDs.
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<Vec<String>>,
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<Box<crate::models::IoExportsComplianceCreateRequestFilters>>,
}

impl IoExportsComplianceCreateRequest {
    pub fn new(num_findings: i32) -> IoExportsComplianceCreateRequest {
        IoExportsComplianceCreateRequest {
            num_findings,
            asset: None,
            filters: None,
        }
    }
}


