/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoFiltersScanList200Response {
    /// A list of filters available for the record type.
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<Vec<crate::models::IoFiltersAgentsList200ResponseFiltersInner>>,
}

impl IoFiltersScanList200Response {
    pub fn new() -> IoFiltersScanList200Response {
        IoFiltersScanList200Response {
            filters: None,
        }
    }
}


