/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoFiltersAgentsList200ResponseFiltersInnerControl {
    /// Provides a human-readable \"hint\" which describes what the filter string should look like.
    #[serde(rename = "readable_regex", skip_serializing_if = "Option::is_none")]
    pub readable_regex: Option<String>,
    /// The type of UI control which represents the filter.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// A regex which can be used by a user interface to validate input.
    #[serde(rename = "regex", skip_serializing_if = "Option::is_none")]
    pub regex: Option<String>,
}

impl IoFiltersAgentsList200ResponseFiltersInnerControl {
    pub fn new() -> IoFiltersAgentsList200ResponseFiltersInnerControl {
        IoFiltersAgentsList200ResponseFiltersInnerControl {
            readable_regex: None,
            r#type: None,
            regex: None,
        }
    }
}


