/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoFiltersAgentsList200ResponseSort : The sorting parameters supported for data returned by the endpoint.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoFiltersAgentsList200ResponseSort {
    /// Maximum number of fields that may be specified for sorting. If this is parameter is not present, any number of fields may be used.
    #[serde(rename = "max_sort_fields", skip_serializing_if = "Option::is_none")]
    pub max_sort_fields: Option<i32>,
    /// Fields by which the returned list of records may be sorted.
    #[serde(rename = "sortable_fields", skip_serializing_if = "Option::is_none")]
    pub sortable_fields: Option<Vec<String>>,
}

impl IoFiltersAgentsList200ResponseSort {
    /// The sorting parameters supported for data returned by the endpoint.
    pub fn new() -> IoFiltersAgentsList200ResponseSort {
        IoFiltersAgentsList200ResponseSort {
            max_sort_fields: None,
            sortable_fields: None,
        }
    }
}


