/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoFiltersAgentsList200ResponseFiltersInner {
    /// The field name to be used in request query strings when applying the filter.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The filter's display label.
    #[serde(rename = "readable_name", skip_serializing_if = "Option::is_none")]
    pub readable_name: Option<String>,
    /// The comparison operators that can be applied to the filter.
    #[serde(rename = "operators", skip_serializing_if = "Option::is_none")]
    pub operators: Option<Vec<String>>,
    #[serde(rename = "control", skip_serializing_if = "Option::is_none")]
    pub control: Option<Box<crate::models::IoFiltersAgentsList200ResponseFiltersInnerControl>>,
    /// Always set to `NULL`. Legacy attribute associated with deprecated functionality.
    #[serde(rename = "group_name", skip_serializing_if = "Option::is_none")]
    pub group_name: Option<String>,
}

impl IoFiltersAgentsList200ResponseFiltersInner {
    pub fn new() -> IoFiltersAgentsList200ResponseFiltersInner {
        IoFiltersAgentsList200ResponseFiltersInner {
            name: None,
            readable_name: None,
            operators: None,
            control: None,
            group_name: None,
        }
    }
}


