/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPluginsFamilyDetailsNameRequest {
    /// The name of the plugin family you want to retrieve the list of plugins for.
    #[serde(rename = "name")]
    pub name: uuid::Uuid,
}

impl IoPluginsFamilyDetailsNameRequest {
    pub fn new(name: uuid::Uuid) -> IoPluginsFamilyDetailsNameRequest {
        IoPluginsFamilyDetailsNameRequest {
            name,
        }
    }
}


