/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPluginsDetails200ResponseAttributesInner {
    /// The name of the attribute.
    #[serde(rename = "attribute_name", skip_serializing_if = "Option::is_none")]
    pub attribute_name: Option<String>,
    /// The value of the attribute.
    #[serde(rename = "attribute_value", skip_serializing_if = "Option::is_none")]
    pub attribute_value: Option<String>,
}

impl IoPluginsDetails200ResponseAttributesInner {
    pub fn new() -> IoPluginsDetails200ResponseAttributesInner {
        IoPluginsDetails200ResponseAttributesInner {
            attribute_name: None,
            attribute_value: None,
        }
    }
}


