/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPluginsList200Response {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::IoPluginsList200ResponseData>>,
    /// The number of records in the returned result set.
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Box<crate::models::IoPluginsList200ResponseParams>>,
    /// The total number of available plugin records after Tenable Vulnerability Management applies the last_updated filter.
    #[serde(rename = "total_count", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<i32>,
}

impl IoPluginsList200Response {
    pub fn new() -> IoPluginsList200Response {
        IoPluginsList200Response {
            data: None,
            size: None,
            params: None,
            total_count: None,
        }
    }
}


