/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPluginsList200ResponseDataPluginDetailsInner {
    /// The ID of the plugin.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The name of the plugin.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The plugin attributes. For more information, see [Tenable Plugin Attributes](/docs/tenable-plugin-attributes).
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Vec<crate::models::IoPluginsList200ResponseDataPluginDetailsInnerAttributesInner>>,
}

impl IoPluginsList200ResponseDataPluginDetailsInner {
    pub fn new() -> IoPluginsList200ResponseDataPluginDetailsInner {
        IoPluginsList200ResponseDataPluginDetailsInner {
            id: None,
            name: None,
            attributes: None,
        }
    }
}


