/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPluginsList200ResponseData {
    #[serde(rename = "plugin_details", skip_serializing_if = "Option::is_none")]
    pub plugin_details: Option<Vec<crate::models::IoPluginsList200ResponseDataPluginDetailsInner>>,
}

impl IoPluginsList200ResponseData {
    pub fn new() -> IoPluginsList200ResponseData {
        IoPluginsList200ResponseData {
            plugin_details: None,
        }
    }
}


