/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPluginsList200ResponseDataPluginDetailsInnerAttributesInnerVpr : Information about the Vulnerability Priority Rating (VPR) for the plugin.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPluginsList200ResponseDataPluginDetailsInnerAttributesInnerVpr {
    /// The Vulnerability Priority Rating (VPR) for the vulnerability. If a plugin is designed to detect multiple vulnerabilities, the VPR represents the highest value calculated for a vulnerability associated with the plugin. For more information, see <a href=\"https://docs.tenable.com/cloud/Content/Analysis/RiskMetrics.htm\" target=\"_blank\">Severity vs. VPR</a> in the <i>Tenable Vulnerability Management User Guide</i>.
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<f32>,
    /// The key drivers Tenable uses to calculate a vulnerability's VPR. For more information, see <a href=\"/docs/vpr-drivers-tio\">Vulnerability Priority Rating Drivers</a>.
    #[serde(rename = "drivers", skip_serializing_if = "Option::is_none")]
    pub drivers: Option<serde_json::Value>,
    /// The ISO timestamp when Tenable Vulnerability Management last imported the VPR for this vulnerability. Vulnerability Management imports updated VPR values every time you run a scan.
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
}

impl IoPluginsList200ResponseDataPluginDetailsInnerAttributesInnerVpr {
    /// Information about the Vulnerability Priority Rating (VPR) for the plugin.
    pub fn new() -> IoPluginsList200ResponseDataPluginDetailsInnerAttributesInnerVpr {
        IoPluginsList200ResponseDataPluginDetailsInnerAttributesInnerVpr {
            score: None,
            drivers: None,
            updated: None,
        }
    }
}


