/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoPluginsList200ResponseParams : The URL query parameters for the returned data set. If the request does not specify the parameters, contains default values.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPluginsList200ResponseParams {
    /// The result set page index. For example, if page size is 10, page 2 contains records 10-19. Default value is 1.
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
    /// The result set page size. Default value is 1,000.
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
    /// The 'last_updated' filter value.
    #[serde(rename = "last_updated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,
}

impl IoPluginsList200ResponseParams {
    /// The URL query parameters for the returned data set. If the request does not specify the parameters, contains default values.
    pub fn new() -> IoPluginsList200ResponseParams {
        IoPluginsList200ResponseParams {
            page: None,
            size: None,
            last_updated: None,
        }
    }
}


