/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoScansRemediationCreateRequest {
    /// The UUID for the Tenable-provided remediation scan template to use. Use the [GET /editor/remediation/templates](ref:editor-list-templates) endpoint to find remediation scan template UUIDs.
    #[serde(rename = "uuid")]
    pub uuid: String,
    #[serde(rename = "settings")]
    pub settings: Box<crate::models::IoScansRemediationCreateRequestSettings>,
    #[serde(rename = "credentials", skip_serializing_if = "Option::is_none")]
    pub credentials: Option<Box<crate::models::ScansCreateRequestCredentials>>,
    /// A comma-delimited list of plugins IDs to add to a remediation scan. You can use the [GET /plugins/families](ref:io-plugins-families-list) and [GET /plugins/families/{id}](ref:io-plugins-family-details) endpoints to get a list of plugin families and plugins to add to the scan.  **Note:** This parameter is only valid for remediation scans. For more information on remediation scans and examples, see [Manage Remediation Scans](doc:io-manage-remediation-scans).
    #[serde(rename = "enabled_plugins", skip_serializing_if = "Option::is_none")]
    pub enabled_plugins: Option<Vec<i32>>,
}

impl IoScansRemediationCreateRequest {
    pub fn new(uuid: String, settings: crate::models::IoScansRemediationCreateRequestSettings) -> IoScansRemediationCreateRequest {
        IoScansRemediationCreateRequest {
            uuid,
            settings: Box::new(settings),
            credentials: None,
            enabled_plugins: None,
        }
    }
}


