/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoScansCredentialsConvert200Response {
    /// The UUID of the new managed credentials.
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
}

impl IoScansCredentialsConvert200Response {
    pub fn new() -> IoScansCredentialsConvert200Response {
        IoScansCredentialsConvert200Response {
            uuid: None,
        }
    }
}


