/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoScansRemediationCreateRequestSettings {
    /// The name of the scan.
    #[serde(rename = "name")]
    pub name: String,
    /// The description of the scan.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The unique ID of the scanner to use. Use the [GET /scanners](ref:scanners-list) endpoint to find the scanner ID. You can use the special value `AUTO-ROUTED` to assign scan targets to scanner groups based on the groups' configured scan routes. For more information, see [Manage Scan Routing](doc:manage-scan-routing-tio).  **Note:** If you omit this parameter from the request, Tenable.io assigns the US Cloud Scanner by default.
    #[serde(rename = "scanner_id", skip_serializing_if = "Option::is_none")]
    pub scanner_id: Option<String>,
    /// For remediation scans, enter a valid target network UUID from a previous scan you wish to remediate.
    #[serde(rename = "target_network_uuid", skip_serializing_if = "Option::is_none")]
    pub target_network_uuid: Option<String>,
    /// This parameter depends on the type of scan: <ul><li>For Nessus agent scans, `scan_time_window` is the time frame, in minutes, during which agents must transmit scan results to Tenable.io in order to be included in dashboards and reports. If your request omits this parameter, the default value is 180 minutes.</li><li>For Nessus scanner scans, `scan_time_window` is the time frame, in minutes, after which the scan will automatically stop. If your request omits this parameter, the default value is 0 and the scan will not stop after a certain time frame.</li></ul>
    #[serde(rename = "scan_time_window", skip_serializing_if = "Option::is_none")]
    pub scan_time_window: Option<i32>,
    /// The list of targets to scan. For a full list of supported target formats, see the [Tenable Vulnerability Management User Guide](https://docs.tenable.com/vulnerability-management/Content/Scans/AboutScanTargets.htm). You can specify multiple targets (of differing formats) as a comma-delimited list.   This parameter is required if your request omits other target parameters. For more information, see \"Required Scan Target Parameters\" in [Create a Scan](doc:create-scan-tio).    For remediation scans, enter a valid target from a previous scan you wish to remediate.   **Note:** Tenable.io does not perform validation on values you submit for this parameter. If you submit invalid values, Tenable.io stores the invalid values in the scan configuration, and when the scan runs, scanning fails on the invalid targets.
    #[serde(rename = "text_targets", skip_serializing_if = "Option::is_none")]
    pub text_targets: Option<String>,
    /// For remediation scans, enter a valid target group ID from a previous scan you wish to remediate.
    #[serde(rename = "target_groups", skip_serializing_if = "Option::is_none")]
    pub target_groups: Option<Vec<i32>>,
    /// The name of a file containing the list of targets to scan. Before you use this parameter, use the [POST /files/upload](ref:file-upload) endpoint to upload the file to Tenable.io; then, use the `fileuploaded` attribute of the response message as the `file_targets` parameter value.  This parameter is required if your request omits other target parameters. For more information, see \"Required Scan Target Parameters\" in [Create a Scan](doc:create-scan-tio).   **Note:** Unicode/UTF-8 encoding is not supported in the targets file.
    #[serde(rename = "file_targets", skip_serializing_if = "Option::is_none")]
    pub file_targets: Option<String>,
    /// The list of asset tag identifiers that the scan uses to determine which assets it evaluates. For more information about tag-based scans, see [Manage Tag-Based Scans](doc:manage-tag-based-scans-tio).  This parameter is required if your request omits other target parameters. For more information, see \"Required Scan Target Parameters\" in [Create a Scan](doc:create-scan-tio).
    #[serde(rename = "tag_targets", skip_serializing_if = "Option::is_none")]
    pub tag_targets: Option<Vec<String>>,
    /// An array of agent group UUIDs to scan. Required if the scan is an agent scan.
    #[serde(rename = "agent_group_id", skip_serializing_if = "Option::is_none")]
    pub agent_group_id: Option<Vec<String>>,
    /// A comma-separated list of accounts that receive the email summary report.
    #[serde(rename = "emails", skip_serializing_if = "Option::is_none")]
    pub emails: Option<String>,
    /// An array containing permissions to apply to the scan.
    #[serde(rename = "acls", skip_serializing_if = "Option::is_none")]
    pub acls: Option<Vec<crate::models::ScansCreateRequestSettingsAclsInner>>,
}

impl IoScansRemediationCreateRequestSettings {
    pub fn new(name: String) -> IoScansRemediationCreateRequestSettings {
        IoScansRemediationCreateRequestSettings {
            name,
            description: None,
            scanner_id: None,
            target_network_uuid: None,
            scan_time_window: None,
            text_targets: None,
            target_groups: None,
            file_targets: None,
            tag_targets: None,
            agent_group_id: None,
            emails: None,
            acls: None,
        }
    }
}


