/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoScansCount200Response {
    /// The number of active and inactive scans in your container. If the `active` query parameter is set to `true` then the count only includes active scans.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
}

impl IoScansCount200Response {
    pub fn new() -> IoScansCount200Response {
        IoScansCount200Response {
            count: None,
        }
    }
}


