/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoV3AssetAttributesAssignedList200ResponseAttributesInner {
    /// the `attribute-id` of the Custom Attribute created by the Admin in a specific container
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// the `name` of the Custom Attribute created by the Admin in a specific container
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// the `value` of the Custom Attribute assigned on an asset.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl IoV3AssetAttributesAssignedList200ResponseAttributesInner {
    pub fn new() -> IoV3AssetAttributesAssignedList200ResponseAttributesInner {
        IoV3AssetAttributesAssignedList200ResponseAttributesInner {
            id: None,
            name: None,
            value: None,
        }
    }
}


