/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoV3AssetAttributesList200ResponseAttributesInner {
    /// UUID of the Custom Attribute created by the Admin in a specific container
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// name of the Custom Attribute created by the Admin in a specific container
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// description of the Custom Attribute created by the Admin in a specific container
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl IoV3AssetAttributesList200ResponseAttributesInner {
    pub fn new() -> IoV3AssetAttributesList200ResponseAttributesInner {
        IoV3AssetAttributesList200ResponseAttributesInner {
            id: None,
            name: None,
            description: None,
        }
    }
}


