/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoV3AssetAttributesList200Response {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Vec<crate::models::IoV3AssetAttributesList200ResponseAttributesInner>>,
}

impl IoV3AssetAttributesList200Response {
    pub fn new() -> IoV3AssetAttributesList200Response {
        IoV3AssetAttributesList200Response {
            attributes: None,
        }
    }
}


