/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoV3AssetAttributesCreateRequestAttributesInner {
    /// The name of the custom asset attribute that you want to create. For example, `Location`.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// A description of the custom asset attribute.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl IoV3AssetAttributesCreateRequestAttributesInner {
    pub fn new() -> IoV3AssetAttributesCreateRequestAttributesInner {
        IoV3AssetAttributesCreateRequestAttributesInner {
            name: None,
            description: None,
        }
    }
}


