/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoV3AssetAttributesSingleUpdateRequest {
    /// The value of the custom asset attribute. For example, for a custom asset attribute named `Location` you could assign a value of `Dallas`.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl IoV3AssetAttributesSingleUpdateRequest {
    pub fn new() -> IoV3AssetAttributesSingleUpdateRequest {
        IoV3AssetAttributesSingleUpdateRequest {
            value: None,
        }
    }
}


