/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoV3AssetAttributesAssignRequest {
    /// An array of custom asset attribute values to assign to the specified asset.
    #[serde(rename = "attributes")]
    pub attributes: Vec<crate::models::IoV3AssetAttributesAssignRequestAttributesInner>,
}

impl IoV3AssetAttributesAssignRequest {
    pub fn new(attributes: Vec<crate::models::IoV3AssetAttributesAssignRequestAttributesInner>) -> IoV3AssetAttributesAssignRequest {
        IoV3AssetAttributesAssignRequest {
            attributes,
        }
    }
}


