/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PoliciesDetails200Response {
    /// The UUID of the Tenable-provided template used to create this policy.
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    #[serde(rename = "audits", skip_serializing_if = "Option::is_none")]
    pub audits: Option<serde_json::Value>,
    #[serde(rename = "credentials", skip_serializing_if = "Option::is_none")]
    pub credentials: Option<serde_json::Value>,
    #[serde(rename = "plugins", skip_serializing_if = "Option::is_none")]
    pub plugins: Option<serde_json::Value>,
    #[serde(rename = "scap", skip_serializing_if = "Option::is_none")]
    pub scap: Option<serde_json::Value>,
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<serde_json::Value>,
}

impl PoliciesDetails200Response {
    pub fn new() -> PoliciesDetails200Response {
        PoliciesDetails200Response {
            uuid: None,
            audits: None,
            credentials: None,
            plugins: None,
            scap: None,
            settings: None,
        }
    }
}


