/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PoliciesCreateRequest {
    /// The uuid for the editor template to use.
    #[serde(rename = "uuid")]
    pub uuid: String,
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<serde_json::Value>,
}

impl PoliciesCreateRequest {
    pub fn new(uuid: String) -> PoliciesCreateRequest {
        PoliciesCreateRequest {
            uuid,
            settings: None,
        }
    }
}


