/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScansDetails404Response : Error message



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScansDetails404Response {
    /// A brief description of the cause of the error.
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl ScansDetails404Response {
    /// Error message
    pub fn new() -> ScansDetails404Response {
        ScansDetails404Response {
            error: None,
        }
    }
}


