/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScansCreateRequestPluginsWebServersIndividual : A list of individual plugins within the specified plugin family.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScansCreateRequestPluginsWebServersIndividual {
    /// The status (`enabled` or `disabled`) of the individual plugin within the plugin family to add to the scan.
    #[serde(rename = "11213", skip_serializing_if = "Option::is_none")]
    pub param_11213: Option<Enum11213>,
    /// The status (`enabled` or `disabled`) of the individual plugin within the plugin family to add to the scan.
    #[serde(rename = "18261", skip_serializing_if = "Option::is_none")]
    pub param_18261: Option<Enum18261>,
}

impl ScansCreateRequestPluginsWebServersIndividual {
    /// A list of individual plugins within the specified plugin family.
    pub fn new() -> ScansCreateRequestPluginsWebServersIndividual {
        ScansCreateRequestPluginsWebServersIndividual {
            param_11213: None,
            param_18261: None,
        }
    }
}

/// The status (`enabled` or `disabled`) of the individual plugin within the plugin family to add to the scan.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Enum11213 {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for Enum11213 {
    fn default() -> Enum11213 {
        Self::Enabled
    }
}
/// The status (`enabled` or `disabled`) of the individual plugin within the plugin family to add to the scan.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Enum18261 {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for Enum18261 {
    fn default() -> Enum18261 {
        Self::Enabled
    }
}

