/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScansCreateRequestSettingsTriggersInner {
    /// The type of scan launch trigger (periodic or file-exists).
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Box<crate::models::ScansCreateRequestSettingsTriggersInnerOptions>>,
}

impl ScansCreateRequestSettingsTriggersInner {
    pub fn new() -> ScansCreateRequestSettingsTriggersInner {
        ScansCreateRequestSettingsTriggersInner {
            r#type: None,
            options: None,
        }
    }
}

/// The type of scan launch trigger (periodic or file-exists).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "periodic")]
    Periodic,
    #[serde(rename = "file-exists")]
    FileExists,
}

impl Default for Type {
    fn default() -> Type {
        Self::Periodic
    }
}

