/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScansCreateRequestPluginsWebServers : A list of plugin families containing individual plugins to add to the scan. Use the [GET /plugins/families](ref:io-plugins-families-list) endpoint to get a list of plugin families.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScansCreateRequestPluginsWebServers {
    #[serde(rename = "individual", skip_serializing_if = "Option::is_none")]
    pub individual: Option<Box<crate::models::ScansCreateRequestPluginsWebServersIndividual>>,
}

impl ScansCreateRequestPluginsWebServers {
    /// A list of plugin families containing individual plugins to add to the scan. Use the [GET /plugins/families](ref:io-plugins-families-list) endpoint to get a list of plugin families.
    pub fn new() -> ScansCreateRequestPluginsWebServers {
        ScansCreateRequestPluginsWebServers {
            individual: None,
        }
    }
}


