/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScansDetails200ResponseHistoryInner {
    /// The unique ID of the historical data.
    #[serde(rename = "history_id", skip_serializing_if = "Option::is_none")]
    pub history_id: Option<i32>,
    /// The unique ID of the owner of the scan.
    #[serde(rename = "owner_id", skip_serializing_if = "Option::is_none")]
    pub owner_id: Option<i32>,
    /// The creation date for the historical data in Unix time.
    #[serde(rename = "creation_date", skip_serializing_if = "Option::is_none")]
    pub creation_date: Option<i32>,
    /// The last modification date for the historical data in Unix time.
    #[serde(rename = "last_modification_date", skip_serializing_if = "Option::is_none")]
    pub last_modification_date: Option<i32>,
    /// The UUID of the historical data.
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
    /// The type of scan: `local` (a credentialed scan performed over the network), `remote` (an uncredentialed scan performed over the network, `agent` (a scan on a local host that a Nessus agent performs directly), or `null` (the scan has never been launched, or the scan is imported).
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// The terminal status of the scan run. For a list of possible values, see [Scan Status](doc:scan-status-tio).
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// If `true`, Tenable.io launched the scan automatically from a schedule.
    #[serde(rename = "scheduler", skip_serializing_if = "Option::is_none")]
    pub scheduler: Option<i32>,
    /// If `true`, Tenable.io did not not launched with a target list. This parameter is `true` for agent scans.
    #[serde(rename = "alt_targets_used", skip_serializing_if = "Option::is_none")]
    pub alt_targets_used: Option<bool>,
    /// Indicates whether the scan results are older than 35 days (`true`). If this parameter is `true`, Tenable.io returns limited data for the scan run. For complete scan results that are older than 35 days, use the [POST /scans/{scan_id}/export](ref:scans-export-request) endpoint instead.
    #[serde(rename = "is_archived", skip_serializing_if = "Option::is_none")]
    pub is_archived: Option<bool>,
}

impl ScansDetails200ResponseHistoryInner {
    pub fn new() -> ScansDetails200ResponseHistoryInner {
        ScansDetails200ResponseHistoryInner {
            history_id: None,
            owner_id: None,
            creation_date: None,
            last_modification_date: None,
            uuid: None,
            r#type: None,
            status: None,
            scheduler: None,
            alt_targets_used: None,
            is_archived: None,
        }
    }
}


