/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScansHistory200ResponsePaginationSortInner {
    /// The field on which Tenable.io sorted the results.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The direction of the sort order. Supported values are `asc` (ascending) and `desc` (descending).
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<String>,
}

impl ScansHistory200ResponsePaginationSortInner {
    pub fn new() -> ScansHistory200ResponsePaginationSortInner {
        ScansHistory200ResponsePaginationSortInner {
            name: None,
            order: None,
        }
    }
}


