/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScansDetails200ResponseVulnerabilitiesInner {
    /// The number of vulnerabilities found.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// The name of the vulnerability plugin.
    #[serde(rename = "plugin_name", skip_serializing_if = "Option::is_none")]
    pub plugin_name: Option<String>,
    /// The index of the vulnerability plugin.
    #[serde(rename = "vuln_index", skip_serializing_if = "Option::is_none")]
    pub vuln_index: Option<i32>,
    /// The severity rating of the plugin.
    #[serde(rename = "severity", skip_serializing_if = "Option::is_none")]
    pub severity: Option<i32>,
    /// The unique ID of the vulnerability plugin.
    #[serde(rename = "plugin_id", skip_serializing_if = "Option::is_none")]
    pub plugin_id: Option<i32>,
    /// The severity index order of the plugin.
    #[serde(rename = "severity_index", skip_serializing_if = "Option::is_none")]
    pub severity_index: Option<i32>,
    /// The parent family of the vulnerability plugin.
    #[serde(rename = "plugin_family", skip_serializing_if = "Option::is_none")]
    pub plugin_family: Option<String>,
}

impl ScansDetails200ResponseVulnerabilitiesInner {
    pub fn new() -> ScansDetails200ResponseVulnerabilitiesInner {
        ScansDetails200ResponseVulnerabilitiesInner {
            count: None,
            plugin_name: None,
            vuln_index: None,
            severity: None,
            plugin_id: None,
            severity_index: None,
            plugin_family: None,
        }
    }
}


