/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScansCreateRequestSettingsAclsInner {
    /// The scan permission. For more information, see [Permissions](doc:permissions).
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<i32>,
    /// A value that indicates whether the user or user group specified in the object owns the scan. Possible values include: `null` (system-owned permissions), `0` (the user is not the owner of the scan), `1` (the user is the owner of the scan).
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<i32>,
    /// The name of the user or group granted the specified permissions, as it appears in the Tenable.io user interface.
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// The name of the user or group granted the specified permissions.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// A number representing the order in which the user or user groups display in the Permissions tab in the Tenable.io user interface.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The type of scan permissions: `default` (default permissions for the scan), `user` (permissions for an individual user), or `group` (permissions for a user group).
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl ScansCreateRequestSettingsAclsInner {
    pub fn new() -> ScansCreateRequestSettingsAclsInner {
        ScansCreateRequestSettingsAclsInner {
            permissions: None,
            owner: None,
            display_name: None,
            name: None,
            id: None,
            r#type: None,
        }
    }
}


