/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScansList200Response {
    #[serde(rename = "scans", skip_serializing_if = "Option::is_none")]
    pub scans: Option<Vec<crate::models::ScansList200ResponseScansInner>>,
    #[serde(rename = "folders", skip_serializing_if = "Option::is_none")]
    pub folders: Option<Vec<crate::models::FoldersList200ResponseInner>>,
    /// The Unix timestamp when Tenable.io received the list request.
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i32>,
}

impl ScansList200Response {
    pub fn new() -> ScansList200Response {
        ScansList200Response {
            scans: None,
            folders: None,
            timestamp: None,
        }
    }
}


