/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScansDetails200ResponseComphostsInner {
    /// The total number of checks considered on the host.
    #[serde(rename = "totalchecksconsidered", skip_serializing_if = "Option::is_none")]
    pub totalchecksconsidered: Option<i32>,
    /// The number of checks considered on the host.
    #[serde(rename = "numchecksconsidered", skip_serializing_if = "Option::is_none")]
    pub numchecksconsidered: Option<i32>,
    /// The total scan progress for the host.
    #[serde(rename = "scanprogresstotal", skip_serializing_if = "Option::is_none")]
    pub scanprogresstotal: Option<i32>,
    /// The current scan progress for the host.
    #[serde(rename = "scanprogresscurrent", skip_serializing_if = "Option::is_none")]
    pub scanprogresscurrent: Option<i32>,
    /// The index for the host.
    #[serde(rename = "host_index", skip_serializing_if = "Option::is_none")]
    pub host_index: Option<String>,
    /// The overall score for the host.
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<i32>,
    #[serde(rename = "severitycount", skip_serializing_if = "Option::is_none")]
    pub severitycount: Option<serde_json::Value>,
    /// The scan progress of the host.
    #[serde(rename = "progress", skip_serializing_if = "Option::is_none")]
    pub progress: Option<String>,
    /// The percentage of critical findings on the host.
    #[serde(rename = "critical", skip_serializing_if = "Option::is_none")]
    pub critical: Option<i32>,
    /// The percentage of high findings on the host.
    #[serde(rename = "high", skip_serializing_if = "Option::is_none")]
    pub high: Option<i32>,
    /// The percentage of medium findings on the host.
    #[serde(rename = "medium", skip_serializing_if = "Option::is_none")]
    pub medium: Option<i32>,
    /// The percentage of low findings on the host.
    #[serde(rename = "low", skip_serializing_if = "Option::is_none")]
    pub low: Option<i32>,
    /// The percentage of info findings on the host.
    #[serde(rename = "info", skip_serializing_if = "Option::is_none")]
    pub info: Option<i32>,
    /// The unique ID of the host.
    #[serde(rename = "host_id", skip_serializing_if = "Option::is_none")]
    pub host_id: Option<i32>,
    /// The name of the host.
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
}

impl ScansDetails200ResponseComphostsInner {
    pub fn new() -> ScansDetails200ResponseComphostsInner {
        ScansDetails200ResponseComphostsInner {
            totalchecksconsidered: None,
            numchecksconsidered: None,
            scanprogresstotal: None,
            scanprogresscurrent: None,
            host_index: None,
            score: None,
            severitycount: None,
            progress: None,
            critical: None,
            high: None,
            medium: None,
            low: None,
            info: None,
            host_id: None,
            hostname: None,
        }
    }
}


