/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScansConfigureRequestCredentialsAdd : A credentials object you want to add to the scan. The parameters of the object vary based on credentials category, credentials type, and type-specific settings. For more information, see [Add Credentials to a Scan](doc:add-credentials-to-scan).   **Note:** This form displays limited parameters that support a Windows type of credentials that uses password authentication.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScansConfigureRequestCredentialsAdd {
    #[serde(rename = "Host", skip_serializing_if = "Option::is_none")]
    pub host: Option<Box<crate::models::ScansCreateRequestCredentialsAddHost>>,
}

impl ScansConfigureRequestCredentialsAdd {
    /// A credentials object you want to add to the scan. The parameters of the object vary based on credentials category, credentials type, and type-specific settings. For more information, see [Add Credentials to a Scan](doc:add-credentials-to-scan).   **Note:** This form displays limited parameters that support a Windows type of credentials that uses password authentication.
    pub fn new() -> ScansConfigureRequestCredentialsAdd {
        ScansConfigureRequestCredentialsAdd {
            host: None,
        }
    }
}


