/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScansHistory200ResponseHistoryInner {
    /// The Unix timestamp when the scan finished running.
    #[serde(rename = "time_end", skip_serializing_if = "Option::is_none")]
    pub time_end: Option<i32>,
    /// The UUID for the specific scan run.
    #[serde(rename = "scan_uuid", skip_serializing_if = "Option::is_none")]
    pub scan_uuid: Option<String>,
    /// The unique identifier for the specific scan run.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Indicates whether the scan results are older than 35 days (`true`). If this parameter is `true`, Tenable.io returns limited data for the scan run. For complete scan results that are older than 35 days, use the [POST /scans/{scan_id}/export](ref:scans-export-request) endpoint instead.
    #[serde(rename = "is_archived", skip_serializing_if = "Option::is_none")]
    pub is_archived: Option<bool>,
    /// The Unix timestamp when the scan started running.
    #[serde(rename = "time_start", skip_serializing_if = "Option::is_none")]
    pub time_start: Option<i32>,
    /// The visibility of the scan results in workbenches (`public` or `private`).
    #[serde(rename = "visibility", skip_serializing_if = "Option::is_none")]
    pub visibility: Option<String>,
    #[serde(rename = "targets", skip_serializing_if = "Option::is_none")]
    pub targets: Option<Box<crate::models::ScansHistory200ResponseHistoryInnerTargets>>,
    /// The status of the scan. For a list of possible values, see [Scan Status](doc:scan-status-tio).
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl ScansHistory200ResponseHistoryInner {
    pub fn new() -> ScansHistory200ResponseHistoryInner {
        ScansHistory200ResponseHistoryInner {
            time_end: None,
            scan_uuid: None,
            id: None,
            is_archived: None,
            time_start: None,
            visibility: None,
            targets: None,
            status: None,
        }
    }
}


