/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScansLaunch200Response {
    /// The UUID of the scan launched.
    #[serde(rename = "scan_uuid", skip_serializing_if = "Option::is_none")]
    pub scan_uuid: Option<String>,
}

impl ScansLaunch200Response {
    pub fn new() -> ScansLaunch200Response {
        ScansLaunch200Response {
            scan_uuid: None,
        }
    }
}


