/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScansPluginOutput200ResponseInfo {
    /// The host's fully qualified domain name; optional.
    #[serde(rename = "host-fqdn", skip_serializing_if = "Option::is_none")]
    pub host_fqdn: Option<String>,
    /// The host's IPv4 address; optional.
    #[serde(rename = "host-ip", skip_serializing_if = "Option::is_none")]
    pub host_ip: Option<String>,
    /// The host's UUID generated by Tenable.io for identification purposes; always present.
    #[serde(rename = "host-uuid", skip_serializing_if = "Option::is_none")]
    pub host_uuid: Option<String>,
    /// The last time a scan was started for this host as an ISO 8601 timestamp; always present.
    #[serde(rename = "host_start", skip_serializing_if = "Option::is_none")]
    pub host_start: Option<String>,
    /// The last time a scan was completed for this host as an ISO 8601 timestamp; always present.
    #[serde(rename = "host_end", skip_serializing_if = "Option::is_none")]
    pub host_end: Option<String>,
    /// The host's mac addresses in a newline-separated list; optional.
    #[serde(rename = "mac-address", skip_serializing_if = "Option::is_none")]
    pub mac_address: Option<String>,
}

impl ScansPluginOutput200ResponseInfo {
    pub fn new() -> ScansPluginOutput200ResponseInfo {
        ScansPluginOutput200ResponseInfo {
            host_fqdn: None,
            host_ip: None,
            host_uuid: None,
            host_start: None,
            host_end: None,
            mac_address: None,
        }
    }
}


