/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScansHistory200Response {
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<crate::models::ScansHistory200ResponsePagination>>,
    #[serde(rename = "history", skip_serializing_if = "Option::is_none")]
    pub history: Option<Vec<crate::models::ScansHistory200ResponseHistoryInner>>,
}

impl ScansHistory200Response {
    pub fn new() -> ScansHistory200Response {
        ScansHistory200Response {
            pagination: None,
            history: None,
        }
    }
}


