/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScansHistory200ResponseHistoryInnerTargets : The target parameters used to launch the scan.



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScansHistory200ResponseHistoryInnerTargets {
    /// If `true`, custom parameters were used to launch the scan.
    #[serde(rename = "custom", skip_serializing_if = "Option::is_none")]
    pub custom: Option<bool>,
    /// If `true`, default parameters were used to launch the scan.
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<bool>,
}

impl ScansHistory200ResponseHistoryInnerTargets {
    /// The target parameters used to launch the scan.
    pub fn new() -> ScansHistory200ResponseHistoryInnerTargets {
        ScansHistory200ResponseHistoryInnerTargets {
            custom: None,
            default: None,
        }
    }
}


