/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScansExportRequest200Response {
    #[serde(rename = "file", skip_serializing_if = "Option::is_none")]
    pub file: Option<String>,
    #[serde(rename = "temp_token", skip_serializing_if = "Option::is_none")]
    pub temp_token: Option<String>,
}

impl ScansExportRequest200Response {
    pub fn new() -> ScansExportRequest200Response {
        ScansExportRequest200Response {
            file: None,
            temp_token: None,
        }
    }
}


