/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScansPluginOutput200Response {
    #[serde(rename = "output", skip_serializing_if = "Option::is_none")]
    pub output: Option<Vec<crate::models::ScansPluginOutput200ResponseOutputInner>>,
    #[serde(rename = "info", skip_serializing_if = "Option::is_none")]
    pub info: Option<Box<crate::models::ScansPluginOutput200ResponseInfo>>,
}

impl ScansPluginOutput200Response {
    pub fn new() -> ScansPluginOutput200Response {
        ScansPluginOutput200Response {
            output: None,
            info: None,
        }
    }
}


