/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScansReadStatusRequest {
    /// If `true`, the scan has been read.
    #[serde(rename = "read")]
    pub read: bool,
}

impl ScansReadStatusRequest {
    pub fn new(read: bool) -> ScansReadStatusRequest {
        ScansReadStatusRequest {
            read,
        }
    }
}


