/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScansDetails200ResponseNotesInner {
    /// The title of the note.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// The specific message of the note.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// The severity of the note.
    #[serde(rename = "severity", skip_serializing_if = "Option::is_none")]
    pub severity: Option<i32>,
}

impl ScansDetails200ResponseNotesInner {
    pub fn new() -> ScansDetails200ResponseNotesInner {
        ScansDetails200ResponseNotesInner {
            title: None,
            message: None,
            severity: None,
        }
    }
}


