/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VmFiltersReportsList200Response {
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<Box<crate::models::VmFiltersReportsList200ResponseFilters>>,
}

impl VmFiltersReportsList200Response {
    pub fn new() -> VmFiltersReportsList200Response {
        VmFiltersReportsList200Response {
            filters: None,
        }
    }
}


