/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VmFiltersReportsList200ResponseFilters {
    /// The field name to be used in request query strings when applying the filter.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The comparison operators that can be applied to the filter.
    #[serde(rename = "operators", skip_serializing_if = "Option::is_none")]
    pub operators: Option<Vec<String>>,
    /// Specifies the datatype of the values that can be used for the filter.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Some filters only allow a specific set of values. For these filters, the list of supported values is returned in this field.
    #[serde(rename = "allowedValues", skip_serializing_if = "Option::is_none")]
    pub allowed_values: Option<Vec<String>>,
}

impl VmFiltersReportsList200ResponseFilters {
    pub fn new() -> VmFiltersReportsList200ResponseFilters {
        VmFiltersReportsList200ResponseFilters {
            name: None,
            operators: None,
            r#type: None,
            allowed_values: None,
        }
    }
}


