/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VmReportsCreate500Response {
    /// The HTTP status code.
    #[serde(rename = "statusCode", skip_serializing_if = "Option::is_none")]
    pub status_code: Option<i32>,
    /// The HTTP status text.
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// A brief message describing the error Tenable Vulnerability Management encountered.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl VmReportsCreate500Response {
    pub fn new() -> VmReportsCreate500Response {
        VmReportsCreate500Response {
            status_code: None,
            error: None,
            message: None,
        }
    }
}


