/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// VmReportsCreateRequestFiltersInnerValue : The value to compare the given property to using the specified operator. Some properties can only be compared to a specific set of values.   You can use the [GET /filters/reports/export](ref:vm-filters-reports-list) endpoint to retrieve the data type and supported values for your chosen filter. For more information, see [Filter Values](doc:vm-report-export-filters#filter-values) in the [Report Export Filters](doc:vm-report-export-filters) document.




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum VmReportsCreateRequestFiltersInnerValue {
    /// The value to compare the given property to using the specified operator. Some properties can only be compared to a specific set of values.   You can use the [GET /filters/reports/export](ref:vm-filters-reports-list) endpoint to retrieve the data type and supported values for your chosen filter. For more information, see [Filter Values](doc:vm-report-export-filters#filter-values) in the [Report Export Filters](doc:vm-report-export-filters) document.
    Strings(Box<Vec<String>>),
    /// The value to compare the given property to using the specified operator. Some properties can only be compared to a specific set of values.   You can use the [GET /filters/reports/export](ref:vm-filters-reports-list) endpoint to retrieve the data type and supported values for your chosen filter. For more information, see [Filter Values](doc:vm-report-export-filters#filter-values) in the [Report Export Filters](doc:vm-report-export-filters) document.
    AssetTags(Box<Vec<crate::models::AssetTagsInner>>),
    /// The value to compare the given property to using the specified operator. Some properties can only be compared to a specific set of values.   You can use the [GET /filters/reports/export](ref:vm-filters-reports-list) endpoint to retrieve the data type and supported values for your chosen filter. For more information, see [Filter Values](doc:vm-report-export-filters#filter-values) in the [Report Export Filters](doc:vm-report-export-filters) document.
    Floats(Box<Vec<f32>>),
    /// The value to compare the given property to using the specified operator. Some properties can only be compared to a specific set of values.   You can use the [GET /filters/reports/export](ref:vm-filters-reports-list) endpoint to retrieve the data type and supported values for your chosen filter. For more information, see [Filter Values](doc:vm-report-export-filters#filter-values) in the [Report Export Filters](doc:vm-report-export-filters) document.
    Integers(Box<Vec<i32>>),
    /// The value to compare the given property to using the specified operator. Some properties can only be compared to a specific set of values.   You can use the [GET /filters/reports/export](ref:vm-filters-reports-list) endpoint to retrieve the data type and supported values for your chosen filter. For more information, see [Filter Values](doc:vm-report-export-filters#filter-values) in the [Report Export Filters](doc:vm-report-export-filters) document.
    Float(Box<f32>),
    /// The value to compare the given property to using the specified operator. Some properties can only be compared to a specific set of values.   You can use the [GET /filters/reports/export](ref:vm-filters-reports-list) endpoint to retrieve the data type and supported values for your chosen filter. For more information, see [Filter Values](doc:vm-report-export-filters#filter-values) in the [Report Export Filters](doc:vm-report-export-filters) document.
    Integer(Box<i32>),
}

impl Default for VmReportsCreateRequestFiltersInnerValue {
    fn default() -> Self {
        *Box::default()
    }
}


