/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VmReportsCreate400Response {
    /// A brief description describing the error.
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl VmReportsCreate400Response {
    pub fn new() -> VmReportsCreate400Response {
        VmReportsCreate400Response {
            error: None,
        }
    }
}


