/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VmReportsCreateRequestFiltersInner {
    /// The property to filter the results by.   You can use the [GET /filters/reports/export](ref:vm-filters-reports-list) endpoint to retrieve a list of valid properties that can be used for filtering. For more information, see [Report Export Filters](doc:vm-report-export-filters).
    #[serde(rename = "property")]
    pub property: String,
    /// The comparison operator to apply to the filter. For example, `eq`, `neq`, `gt`, etc.   You can use the [GET /filters/reports/export](ref:vm-filters-reports-list) endpoint to retrieve a list of supported comparison operators for your chosen filter. For more information, see [Report Export Filters](doc:vm-report-export-filters).
    #[serde(rename = "operator")]
    pub operator: String,
}

impl VmReportsCreateRequestFiltersInner {
    pub fn new(property: String, operator: String, _value: crate::models::VmReportsCreateRequestFiltersInnerValue) -> VmReportsCreateRequestFiltersInner {
        VmReportsCreateRequestFiltersInner {
            property,
            operator,
        }
    }
}


