/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VulnerabilitiesImportV2200Response {
    /// This attribute is always empty. An empty value does not indicate an error condition.
    #[serde(rename = "job_uuid", skip_serializing_if = "Option::is_none")]
    pub job_uuid: Option<String>,
}

impl VulnerabilitiesImportV2200Response {
    pub fn new() -> VulnerabilitiesImportV2200Response {
        VulnerabilitiesImportV2200Response {
            job_uuid: None,
        }
    }
}


