/*
 * Vulnerability Management
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// VulnerabilitiesImportV2RequestCoverage : .



#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VulnerabilitiesImportV2RequestCoverage {
    /// A string or range of IDs that each represents a check that the scan used to detect vulnerabilities you are importing. This parameter supports Tenable plugin checks only. For more information, see [Plugins](https://www.tenable.com/plugins).
    #[serde(rename = "ids", skip_serializing_if = "Option::is_none")]
    pub ids: Option<String>,
}

impl VulnerabilitiesImportV2RequestCoverage {
    /// .
    pub fn new() -> VulnerabilitiesImportV2RequestCoverage {
        VulnerabilitiesImportV2RequestCoverage {
            ids: None,
        }
    }
}


